export const DEFAULT_TEAMS = [
  { id: "usa", name: "United States", code: "USA", flag: "🇺🇸", pot: 1, status: "active", note: "Host" },
  { id: "mex", name: "Mexico", code: "MEX", flag: "🇲🇽", pot: 1, status: "active", note: "Host" },
  { id: "can", name: "Canada", code: "CAN", flag: "🇨🇦", pot: 2, status: "active", note: "Host" },
  { id: "q04", name: "Qualifier 04", code: "Q04", flag: "🏳️", pot: 1, status: "active", note: "Edit when qualified" },
  { id: "q05", name: "Qualifier 05", code: "Q05", flag: "🏳️", pot: 1, status: "active", note: "Edit when qualified" },
  { id: "q06", name: "Qualifier 06", code: "Q06", flag: "🏳️", pot: 1, status: "active", note: "Edit when qualified" },
  { id: "q07", name: "Qualifier 07", code: "Q07", flag: "🏳️", pot: 1, status: "active", note: "Edit when qualified" },
  { id: "q08", name: "Qualifier 08", code: "Q08", flag: "🏳️", pot: 1, status: "active", note: "Edit when qualified" },
  { id: "q09", name: "Qualifier 09", code: "Q09", flag: "🏳️", pot: 1, status: "active", note: "Edit when qualified" },
  { id: "q10", name: "Qualifier 10", code: "Q10", flag: "🏳️", pot: 1, status: "active", note: "Edit when qualified" },
  { id: "q11", name: "Qualifier 11", code: "Q11", flag: "🏳️", pot: 1, status: "active", note: "Edit when qualified" },
  { id: "q12", name: "Qualifier 12", code: "Q12", flag: "🏳️", pot: 1, status: "active", note: "Edit when qualified" },
  { id: "q13", name: "Qualifier 13", code: "Q13", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q14", name: "Qualifier 14", code: "Q14", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q15", name: "Qualifier 15", code: "Q15", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q16", name: "Qualifier 16", code: "Q16", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q17", name: "Qualifier 17", code: "Q17", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q18", name: "Qualifier 18", code: "Q18", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q19", name: "Qualifier 19", code: "Q19", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q20", name: "Qualifier 20", code: "Q20", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q21", name: "Qualifier 21", code: "Q21", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q22", name: "Qualifier 22", code: "Q22", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q23", name: "Qualifier 23", code: "Q23", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q24", name: "Qualifier 24", code: "Q24", flag: "🏳️", pot: 2, status: "active", note: "Edit when qualified" },
  { id: "q25", name: "Qualifier 25", code: "Q25", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q26", name: "Qualifier 26", code: "Q26", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q27", name: "Qualifier 27", code: "Q27", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q28", name: "Qualifier 28", code: "Q28", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q29", name: "Qualifier 29", code: "Q29", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q30", name: "Qualifier 30", code: "Q30", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q31", name: "Qualifier 31", code: "Q31", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q32", name: "Qualifier 32", code: "Q32", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q33", name: "Qualifier 33", code: "Q33", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q34", name: "Qualifier 34", code: "Q34", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q35", name: "Qualifier 35", code: "Q35", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q36", name: "Qualifier 36", code: "Q36", flag: "🏳️", pot: 3, status: "active", note: "Edit when qualified" },
  { id: "q37", name: "Qualifier 37", code: "Q37", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" },
  { id: "q38", name: "Qualifier 38", code: "Q38", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" },
  { id: "q39", name: "Qualifier 39", code: "Q39", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" },
  { id: "q40", name: "Qualifier 40", code: "Q40", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" },
  { id: "q41", name: "Qualifier 41", code: "Q41", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" },
  { id: "q42", name: "Qualifier 42", code: "Q42", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" },
  { id: "q43", name: "Qualifier 43", code: "Q43", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" },
  { id: "q44", name: "Qualifier 44", code: "Q44", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" },
  { id: "q45", name: "Qualifier 45", code: "Q45", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" },
  { id: "q46", name: "Qualifier 46", code: "Q46", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" },
  { id: "q47", name: "Qualifier 47", code: "Q47", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" },
  { id: "q48", name: "Qualifier 48", code: "Q48", flag: "🏳️", pot: 4, status: "active", note: "Edit when qualified" }
];

export const STAGES = [
  { value: "active", label: "Still alive" },
  { value: "group", label: "Group stage" },
  { value: "r32", label: "Round of 32" },
  { value: "r16", label: "Round of 16" },
  { value: "quarter", label: "Quarter-final" },
  { value: "semi", label: "Semi-final" },
  { value: "runner-up", label: "Runner-up" },
  { value: "winner", label: "Winner" },
  { value: "eliminated", label: "Eliminated" }
];
